#!/bin/python3

alias_path = r"/home/timo/.zsh_aliases"
alias_file = open(alias_path,"r")

lines = alias_file.readlines()
alias_file.close()

categories = []
for index,line in enumerate(lines):
    if line[0] == "#":
        categories.append((index,line[1:-1]))
categories.append((len(lines),"New category"))

new_alias = input("New alias: ")
new_command = input("Command: ")
print("Choose category:")
for id, c in enumerate(categories):
    print(id,(c[1]).lstrip())
chosen_category_str = input("Chose a number (default 0): ")
try:
    chosen_category_int = int(chosen_category_str)
except:
    chosen_category_int = 0

if chosen_category_int == len(categories)-1:
    new_category_name = input("Enter name for new category: ")
    lines.append("\n# "+new_category_name+"\n")
lines.insert((categories[chosen_category_int])[0]+1,f"alias {new_alias}=\'{new_command}\'\n")

output_file = open(alias_path,"w")
output_file.writelines(lines)
output_file.close()

